/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-04-24 15:24:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Model.Bean.Detail;
import java.util.LinkedHashMap;
import java.util.ArrayList;
import java.util.List;
import Model.Bean.Product;
import Model.Bean.Account;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.LinkedHashMap");
    _jspx_imports_classes.add("Model.Bean.Account");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("Model.Bean.Detail");
    _jspx_imports_classes.add("Model.Bean.Product");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Home</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta name=\"description\" content=\"----\">\r\n");
      out.write("\r\n");
      out.write("<meta name=\"keywords\" content=\"Premium HTML Template\">\r\n");
      out.write("\r\n");
      out.write("<meta name=\"author\" content=\"HTMLmate\">\r\n");
      out.write("\r\n");
      out.write("<!-- Mobile Specific Meta -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<!-- css-include -->\r\n");
      out.write("\r\n");
      out.write("<!-- boorstrap -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<!-- themify-icon.css -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/themify-icons.css\">\r\n");
      out.write("<!-- owl-carousel -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/owl.carousel.css\">\r\n");
      out.write("<!-- light-box -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/lightbox.css\">\r\n");
      out.write("<!-- video css -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/video.min.css\">\r\n");
      out.write("<!-- menu.css -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/menu.css\">\r\n");
      out.write("<!-- style -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\r\n");
      out.write("<!-- responsive.css -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/responsive.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#numProduct {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	background-color: red;\r\n");
      out.write("	color: white;\r\n");
      out.write("	width: 20px;\r\n");
      out.write("	height: 20px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	border-radius: 50%;\r\n");
      out.write("	top: 0%;\r\n");
      out.write("	right: 0%;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#home-btn-search {\r\n");
      out.write("	border: 1px solid silver;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	padding: 5px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	");

	Account account = (Account) session.getAttribute("account");
	List<Product> products = (ArrayList<Product>) request.getAttribute("products");
	List<Detail> cart = (ArrayList<Detail>) session.getAttribute("cart");
	
      out.write("\r\n");
      out.write("	<div id=\"preloader\"></div>\r\n");
      out.write("	<!-- Start of nav bar \r\n");
      out.write("		============================================= -->\r\n");
      out.write("	<nav id=\"poppin-nav\">\r\n");
      out.write("		<div id=\"nav-off\"></div>\r\n");
      out.write("		<div id=\"header-logo-1\" class=\"text-center\">\r\n");
      out.write("			<a href=\"home\"><img src=\"img/LOGO_CHATAM.png\" alt=\"img\"> ");

 if (account != null) {
 
      out.write(" Admin ");
      out.print(account.getDisplayName());
      out.write(' ');

 } else {
 
      out.write(" Khách hàng ");

 }
 
      out.write(" </a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<ul id=\"menu\">\r\n");
      out.write("			<li class=\"has-submenu text-capitalize\"><a href=\"home\">Home\r\n");
      out.write("					Page </a></li>\r\n");
      out.write("			");

			if (account == null) {
			
      out.write("\r\n");
      out.write("			<li><a href=\"rent\">Product rental</a></li>\r\n");
      out.write("			<li><a href=\"contact.jsp\">Contact</a></li>\r\n");
      out.write("			<li><a href=\"login_form.jsp\">Login</a></li>\r\n");
      out.write("			");

			} else {
			
      out.write("\r\n");
      out.write("			<li><a href=\"admin.jsp\">User</a></li>\r\n");
      out.write("			<li><a href=\"customers\">Customer</a></li>\r\n");
      out.write("			<li><a href=\"invoices\">Invoice</a></li>\r\n");
      out.write("			<li><a href=\"logout\">Log out</a></li>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("		</ul>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<div id=\"menu-overlay\"></div>\r\n");
      out.write("	<!-- End of nav bar \r\n");
      out.write("		============================================= -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Start of header\r\n");
      out.write("		============================================= -->\r\n");
      out.write("	<header id=\"site-header\" class=\"not-stuck\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div id=\"header-logo\">\r\n");
      out.write("					<a href=\"home\"><img src=\"img/LOGO_CHATAM.png\" alt=\"img\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div\r\n");
      out.write("					style=\"float: right; display: flex; justify-content: space-around;\">\r\n");
      out.write("					");

					if (account == null) {
					
      out.write("\r\n");
      out.write("					<div style=\"margin-right: 50px; position: relative;\">\r\n");
      out.write("						<a href=\"cart.jsp\"><img src=\"img/cart.png\" width=\"50\"\r\n");
      out.write("							height=\"50\"></a>\r\n");
      out.write("						<p id=\"numProduct\">\r\n");
      out.write("							");

							if (cart == null || cart.size() == 0) {
							
      out.write("\r\n");
      out.write("							0\r\n");
      out.write("							");

							} else {
							
      out.write("\r\n");
      out.write("							");
      out.print(cart.size());
      out.write("\r\n");
      out.write("							");

							}
							
      out.write("\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					");

					}
					
      out.write("\r\n");
      out.write("					<div id=\"menu-burger\" class=\"pull-right not-stuck\">\r\n");
      out.write("						<div id=\"menu-bar\">\r\n");
      out.write("							<span class=\"icon-bar top\"></span> <span class=\"icon-bar middle\"></span>\r\n");
      out.write("							<span class=\"icon-bar bottom\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<!-- End of header\r\n");
      out.write("		============================================= -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Start of page head section\r\n");
      out.write("		============================================= -->\r\n");
      out.write("	<section id=\"page-head\" class=\"page-head-section\">\r\n");
      out.write("		<div class=\"page-head-overlay\"></div>\r\n");
      out.write("		<div id=\"page-head-effect\" class=\"page-head-effect\">\r\n");
      out.write("			<canvas id=\"demo-canvas\"></canvas>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- // page-head-style -->\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"banner-content\">\r\n");
      out.write("					<div class=\"page-head-content\">\r\n");
      out.write("						<div class=\"page-head-title text-capitalize pb40\">\r\n");
      out.write("							<h1>Home Page</h1>\r\n");
      out.write("							<span class=\"descrip\">Home</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- //title -->\r\n");
      out.write("\r\n");
      out.write("						<div class=\"page-head-social\">\r\n");
      out.write("							<div class=\"social-title text-uppercase\">\r\n");
      out.write("								<span>Nhom4</span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- //title -->\r\n");
      out.write("							<div class=\"page-head-social-item ul-li\">\r\n");
      out.write("								<ul class=\"page-head-social-list\">\r\n");
      out.write("									<li><a href=\"#\"><span class=\"ti-facebook\"></span></a></li>\r\n");
      out.write("									<li><a href=\"#\"><span class=\"ti-twitter-alt\"></span></a></li>\r\n");
      out.write("									<li><a href=\"#\"><span class=\"ti-google\"></span></a></li>\r\n");
      out.write("									<li><a href=\"#\"><span class=\"ti-instagram\"></span></a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<!-- /.page-head-social-list -->\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- /.page-head-social-item -->\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- /.page-head-social -->\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- /.page-head-content -->\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!--  /.row-->\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--  /.container -->\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- End of page head section\r\n");
      out.write("		============================================= -->\r\n");
      out.write("	<!-- Start of portfolio section\r\n");
      out.write("		============================================= -->\r\n");
      out.write("	<section id=\"portfolio\" class=\"portfolio-section\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"portfolio-content\">\r\n");
      out.write("					<div class=\"portfolio-tab pb55\">\r\n");
      out.write("						<div id=\"filters\" class=\"button-group pb45\">\r\n");
      out.write("							<button class=\"tab-button active\" data-filter=\"*\">\r\n");
      out.write("								All<span>13</span>\r\n");
      out.write("							</button>\r\n");
      out.write("							<input oninput=\"searchProducts()\" type=\"search\"\r\n");
      out.write("								id=\"home-btn-search\" class=\"home-btn-search\"\r\n");
      out.write("								placeholder=\"Input product name...\" />\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- /tab-button -->\r\n");
      out.write("\r\n");
      out.write("						<div class=\"portfolio-tab-text-pic row\">\r\n");
      out.write("							<div id=\"posts\">\r\n");
      out.write("								");

								for (Product product : products) {
								
      out.write("\r\n");
      out.write("								<div id=\"");
      out.print(product.getId());
      out.write("\" class=\"item item-grid\">\r\n");
      out.write("									<div class=\"item-wrap\">\r\n");
      out.write("										<div class=\"work-item\">\r\n");
      out.write("											<div class=\"work-pic\">\r\n");
      out.write("												<img src=\"");
      out.print(product.getImage());
      out.write("\" alt=\"image\">\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"hover-content\">\r\n");
      out.write("												<div class=\"hover-text text-center\">\r\n");
      out.write("													<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" data-lightbox=\"roadtrip\"><span\r\n");
      out.write("														class=\"ti-fullscreen\"></span></a>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"project-description text-uppercase ul-li\">\r\n");
      out.write("													<h3>\r\n");
      out.write("														<a href=\"#\">");
      out.print(product.getName());
      out.write("</a>\r\n");
      out.write("													</h3>\r\n");
      out.write("													<ul class=\"project-catagorry text-capitalize\">\r\n");
      out.write("														<li><a href=\"product?id=");
      out.print(product.getId());
      out.write("\">See\r\n");
      out.write("																detail</a></li>\r\n");
      out.write("														<br>\r\n");
      out.write("														<li><a href=\"#\">");
      out.print(product.getPrice());
      out.write("VNĐ </a></li>\r\n");
      out.write("														<br>\r\n");
      out.write("														<li><a href=\"#\"> ");

 if (product.getQuantity() > 0) {
 
      out.write("Stocking");

 } else {
 
      out.write("Sold out");

 }
 
      out.write("\r\n");
      out.write("														</a></li>\r\n");
      out.write("													</ul>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								");

								}
								
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("							<!--//posts-->\r\n");
      out.write("						</div>\r\n");
      out.write("						<!--//portfolio-tab-text-pic-->\r\n");
      out.write("					</div>\r\n");
      out.write("					<!--//portfolio-tab-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<div class=\"poppin-more text-uppercase text-center\">\r\n");
      out.write("						<div class=\"more-btn\">\r\n");
      out.write("							<a href=\"#\">MORE</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- //.more -->\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<!--//portfolio-content -->\r\n");
      out.write("			</div>\r\n");
      out.write("			<!--  /.row -->\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--  /.conatiner -->\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- End of portfolio section\r\n");
      out.write("		============================================= -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Start of newsletter section\r\n");
      out.write("		============================================= -->\r\n");
      out.write("	<section id=\"newsletter\" class=\"newsletter-section\">\r\n");
      out.write("		<div class=\"page-head-overlay\"></div>\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"newsletter-section-content\">\r\n");
      out.write("					<div class=\"newsletter-title pb75\">\r\n");
      out.write("						<h2 class=\"deep-black\">Subscribe On My Newsletter</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"newsletter-form\">\r\n");
      out.write("						<form action=\"#\" class=\"input-group\">\r\n");
      out.write("							<input type=\"email\" class=\"form-control\"\r\n");
      out.write("								placeholder=\"Enter Your Email\"> <span\r\n");
      out.write("								class=\"input-group-addon\">\r\n");
      out.write("								<button type=\"submit\">\r\n");
      out.write("									<span class=\"deep-black ti-arrow-right\"></span>\r\n");
      out.write("								</button>\r\n");
      out.write("							</span>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- //.newsletter-section-content -->\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<!--  /.row -->\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--  /.conatainer -->\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- End of newsletter section\r\n");
      out.write("		============================================= -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Start of our service section\r\n");
      out.write("		============================================= -->\r\n");
      out.write("	<section id=\"service\" class=\"service-section pt90 pb40\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"section-title text-capitalize deep-black pb75\">\r\n");
      out.write("					<h2>Our latest blog</h2>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- //title -->\r\n");
      out.write("\r\n");
      out.write("				<div class=\"latest-blog-content\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-md-4\">\r\n");
      out.write("							<div class=\"latest-blog-text-pic\">\r\n");
      out.write("								<div class=\"latest-blog-img mb10\">\r\n");
      out.write("									<img src=\"img/3.jpg\" alt=\"img\">\r\n");
      out.write("									<div class=\"blog-meta mt20 ul-li\">\r\n");
      out.write("										<ul class=\"meta-list\">\r\n");
      out.write("											<li><a href=\"#\">April 16, 2021 / </a></li>\r\n");
      out.write("											<li><a href=\"#\"> Nhom4 / </a></li>\r\n");
      out.write("											<li><a href=\"#\">News</a></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<!-- //.latest-blog-img -->\r\n");
      out.write("\r\n");
      out.write("								<div class=\"latest-blog-text\">\r\n");
      out.write("									<div class=\"blog-head\">\r\n");
      out.write("										<h2>\r\n");
      out.write("											<a href=\"#\">The champion of the Female Student Volleyball\r\n");
      out.write("												Tournament called name of Faculty of Tourism</a>\r\n");
      out.write("										</h2>\r\n");
      out.write("									</div>\r\n");
      out.write("									<!-- //.blog-head -->\r\n");
      out.write("									<div class=\"blog-details mt15\">\r\n");
      out.write("										<p>Excepteur sint occaecat cupidatat nonmaly proident,\r\n");
      out.write("											sunt.</p>\r\n");
      out.write("									</div>\r\n");
      out.write("									<!-- //.blog-details -->\r\n");
      out.write("									<div class=\"blog-read-more text-capitalize pull-left\">\r\n");
      out.write("										<a href=\"#\">read more<span class=\"ti-arrow-right\"></span></a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<!-- //.blog-read-more -->\r\n");
      out.write("\r\n");
      out.write("									<div class=\"latest-blog-comments text-capitalize pull-right\">\r\n");
      out.write("										<a href=\"#\"><span class=\"ti-comments\"> 5 Comments</span></a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<!-- //.latest-blog-comments -->\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- //.latest-blog-text-pic -->\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- //.col-md-4 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-md-4\">\r\n");
      out.write("							<div class=\"latest-blog-text-pic\">\r\n");
      out.write("								<div class=\"latest-blog-img mb10\">\r\n");
      out.write("									<img src=\"img/1.jpg\" alt=\"img\">\r\n");
      out.write("									<div class=\"blog-meta mt20 ul-li\">\r\n");
      out.write("										<ul class=\"meta-list\">\r\n");
      out.write("											<li><a href=\"#\">April 16, 2017 / </a></li>\r\n");
      out.write("											<li><a href=\"#\"> Nhom4 / </a></li>\r\n");
      out.write("											<li><a href=\"#\">News</a></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<!-- //.latest-blog-img -->\r\n");
      out.write("\r\n");
      out.write("								<div class=\"latest-blog-text\">\r\n");
      out.write("									<div class=\"blog-head\">\r\n");
      out.write("										<h2>\r\n");
      out.write("											<a href=\"#\">The University of Danang participates in the\r\n");
      out.write("												Science Award and Technology of the Ministry of Education in\r\n");
      out.write("												2022</a>\r\n");
      out.write("										</h2>\r\n");
      out.write("									</div>\r\n");
      out.write("									<!-- //.blog-head -->\r\n");
      out.write("									<div class=\"blog-details mt15\">\r\n");
      out.write("										<p>Excepteur sint occaecat cupidatat nonmaly proident,\r\n");
      out.write("											sunt.</p>\r\n");
      out.write("									</div>\r\n");
      out.write("									<!-- //.blog-details -->\r\n");
      out.write("									<div class=\"blog-read-more text-capitalize pull-left\">\r\n");
      out.write("										<a href=\"#\">read more<span class=\"ti-arrow-right\"></span></a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<!-- //.blog-read-more -->\r\n");
      out.write("\r\n");
      out.write("									<div class=\"latest-blog-comments text-capitalize pull-right\">\r\n");
      out.write("										<a href=\"#\"><span class=\"ti-comments\"> 5 Comments</span></a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<!-- //.latest-blog-comments -->\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- //.latest-blog-text-pic -->\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- //.col-md-4 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-md-4\">\r\n");
      out.write("							<div class=\"latest-blog-text-pic\">\r\n");
      out.write("								<div class=\"latest-blog-img mb10\">\r\n");
      out.write("									<img src=\"img/2.jpg\" alt=\"img\">\r\n");
      out.write("									<div class=\"blog-meta mt20 ul-li\">\r\n");
      out.write("										<ul class=\"meta-list\">\r\n");
      out.write("											<li><a href=\"#\">April 16, 2017 / </a></li>\r\n");
      out.write("											<li><a href=\"#\"> Nhom4 / </a></li>\r\n");
      out.write("											<li><a href=\"#\">News</a></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<!-- //.latest-blog-img -->\r\n");
      out.write("\r\n");
      out.write("								<div class=\"latest-blog-text\">\r\n");
      out.write("									<div class=\"blog-head\">\r\n");
      out.write("										<h2>\r\n");
      out.write("											<a href=\"#\">“If you have a dream, follow your passion to\r\n");
      out.write("												the end”</a>\r\n");
      out.write("										</h2>\r\n");
      out.write("									</div>\r\n");
      out.write("									<!-- //.blog-head -->\r\n");
      out.write("									<div class=\"blog-details mt15\">\r\n");
      out.write("										<p>Excepteur sint occaecat cupidatat nonmaly proident,\r\n");
      out.write("											sunt.</p>\r\n");
      out.write("									</div>\r\n");
      out.write("									<!-- //.blog-details -->\r\n");
      out.write("									<div class=\"blog-read-more text-capitalize pull-left\">\r\n");
      out.write("										<a href=\"#\">read more<span class=\"ti-arrow-right\"></span></a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<!-- //.blog-read-more -->\r\n");
      out.write("\r\n");
      out.write("									<div class=\"latest-blog-comments text-capitalize pull-right\">\r\n");
      out.write("										<a href=\"#\"><span class=\"ti-comments\"> 5 Comments</span></a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<!-- //.latest-blog-comments -->\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- //.latest-blog-text-pic -->\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- //.col-md-4 -->\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- //.row -->\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- //.latest-blog-content -->\r\n");
      out.write("			</div>\r\n");
      out.write("			<!--  row -->\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--  container-->\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- End of our service section\r\n");
      out.write("		============================================= -->\r\n");
      out.write("	<!-- Start of footer section\r\n");
      out.write("		============================================= -->\r\n");
      out.write("	<footer>\r\n");
      out.write("		<div class=\"footer-area footer-2\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"copy-right-area text-center\">\r\n");
      out.write("						<div class=\"page-head-social-item ul-li\">\r\n");
      out.write("							<ul class=\"page-head-social-list\">\r\n");
      out.write("								<li><a href=\"#\"><span class=\"ti-facebook\"></span></a></li>\r\n");
      out.write("								<li><a href=\"#\"><span class=\"ti-twitter-alt\"></span></a></li>\r\n");
      out.write("								<li><a href=\"#\"><span class=\"ti-google\"></span></a></li>\r\n");
      out.write("								<li><a href=\"#\"><span class=\"ti-instagram\"></span></a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("							<!-- /.page-head-social-list -->\r\n");
      out.write("						</div>\r\n");
      out.write("						<span>© Nhom4 </span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- //copy-right-area -->\r\n");
      out.write("				</div>\r\n");
      out.write("				<!--  /.container -->\r\n");
      out.write("			</div>\r\n");
      out.write("			<!--  /.row-->\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--  /.footer-area -->\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!-- End of footer section\r\n");
      out.write("		============================================= -->\r\n");
      out.write("	<!--  Js Library -->\r\n");
      out.write("	<script src=\"js/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("	<!-- Include  for bootstrap -->\r\n");
      out.write("	<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("	<!-- Include isotope Js -->\r\n");
      out.write("	<script src=\"js/jquery.isotope.min.js\"></script>\r\n");
      out.write("	<!-- Include lightbox -->\r\n");
      out.write("	<script src=\"js/lightbox.js\"></script>\r\n");
      out.write("	<!-- Include circle-effect.js -->\r\n");
      out.write("	<script src=\"js/circle-effect.js\"></script>\r\n");
      out.write("	<!-- Include Video js -->\r\n");
      out.write("	<script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("	<!-- Include Owl-carousel -->\r\n");
      out.write("	<script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("	<!-- Include Counter up -->\r\n");
      out.write("	<script src=\"js/jquery.counterup.min.js\"></script>\r\n");
      out.write("	<script src=\"js/waypoints.min.js\"></script>\r\n");
      out.write("	<!-- Include script.js -->\r\n");
      out.write("	<script src=\"js/script.js\"></script>\r\n");
      out.write("	<script src=\"js/list-products.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
